language: default  # The actual building happens inside a Docker to have ARM support 

services:
  - docker

before_install:
  - docker build .

script:
  - echo "Success"  # Necessary to avoid travis using 'rake' by default
